eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/xiaomi?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&serverTimezone=Asia/Shanghai
    username: root